name: centOS python3.10.12
on: [push]
jobs:
 build:
  runs-on: ubuntu-22.04
  steps:
  - uses: actions/checkout@v2
  - name: Set Up Python 3.10.12
    uses: actions/setup-python@v1
    with:
      python-version: 3.10.12
  - name: Install dependencies
    run: | 
     pip install requests==2.25.1
     pip install pylint
     make install
  - name: Lint
    run: |
     pip install pytest-cov
     make lint
  - name: Test
    run:
     make test 
