name: centOS python3.6.8
on: [push]
jobs:
 build:
 runs-on: ubuntu-latest
 steps:
 - uses: actions/checkout@v2
 - name: Set up Python 3.6.8
   uses: actions/setup-python@v1
   with:
    python-version: 3.6.8
 - name: Install dependencies
   run: |
    make install
 - name: Lint
    make lint
 - name: Test
   run: |
    make test
