name: centOS python3.10.12
on: [push]
jobs:
 build:
  runs-on: ubuntu-22.04
  steps:
  - uses: actions/checkout@v2.3.4
  - name: Set Up Python 3.10.12
    uses: actions/setup-python@v1
    with:
      python-version: 3.10.12
  - name: Install dependencies
    run: | 
     python3 -m venv env
     source env/bin/activate
     make install
  - name: Lint
    run: |
     pip3 install pylint
     make lint
    
  - name: Test
    run: |
<<<<<<< HEAD
     python3 -m pytest-cov
      
=======
     pip3 install pytest-cov
     make test 
    env: 
     CI: false
>>>>>>> ce042e651df069cf73ac27b52d203ddc9fe7d22c
